on:
  push:
    tags:
    - 'v*'


jobs:
  build_and_release:
    name: Build and release
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Assemble the plugin
      run: cd delay_siblings && zip -r ../delay_siblings.ankiaddon *

    - name: Release
      uses: svenstaro/upload-release-action@1.0.1
      with:
        tag: ${{ github.ref }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: delay_siblings.ankiaddon
        asset_name: delay_siblings.ankiaddon
